
import Head from 'next/head'
import ViewContainer from '@/components/viewContainer'

export default function Home() {
    return (
        <>
            <Head>
                <title>仿掘金站点</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div id='juejin'>
                <ViewContainer />
            </div>
        </>
    )
}
