import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>仿掘金站点</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div id='juejin'>
        <div className='view-container container'>
        <div className='main-header-box'>
        <header className='main-header visiable'>
            <div className='container'>
                <a href="/" className='logo'>
                    <Image src='juejin_big.svg' 
                    width={107}
                    height={22}
                    alt='稀土掘金'
                    className='logo-img'/>
                    <Image src='juejin_small.svg' 
                    width={31}
                    height={22}
                    alt='稀土掘金'
                    className='mobile'/>
                </a>
                <nav className='main-nav'>
                    <ul className='nav-list'>
                        <li className='main-nav-list'>
                            <div className='phone-show-menu'>
                                <span>首页</span>
                            </div>
                            <ul className='phone-hide'>
                                <li className='nav-item linkl-item'>
                                    <a href="/">首页</a>
                                </li>
                                <li className='nav-item linkl-item'>
                                    <a href="/">沸点</a>
                                </li>
                                <li className='nav-item linkl-item'>
                                    <a href="/">课程</a>
                                </li>
                                <li className='nav-item linkl-item'>
                                    <a href="/">直播</a>
                                </li>
                                <li className='nav-item linkl-item'>
                                    <a href="/">活动</a>
                                </li>
                                <li className='nav-item linkl-item'>
                                    <a href="/">竞赛</a>
                                </li>
                                <li className='nav-item linkl-item'>
                                    <a href="/">商城</a>
                                </li>
                            </ul>
                        </li>
                        <ul className='right-side-nav'></ul>
                        </ul>
                </nav>
            </div>
        </header></div>
        <main className='main-container container'>
            <div className='view'>
                <nav className='view-nav'>
                    <div className='nav-list'>
                        <a href="/" className='nav-item active'>综合</a>
                        <a href="/" className='nav-item'>关注</a>
                        <a href="/" className='nav-item'>后端</a>
                        <a href="/" className='nav-item'>前端</a>
                        <a href="/" className='nav-item'>Android</a>
                        <a href="/" className='nav-item'>ios</a>
                        <a href="/" className='nav-item'>人工智能</a>
                        <a href="/" className='nav-item'>开发工具</a>
                        <a href="/" className='nav-item'>代码人生</a>
                        <a href="/" className='nav-item'>阅读</a>
                    </div>
                </nav>
                <div className='timeline-container'>
                    <div className='timeline-content'>
                        <div className='timeline-entry-list'>
                            <div className='entry-list-container'>
                                <div className='list-header'>
                                    <nav className='list-nav'>
                                        <ul className='nav-list'>
                                            <li className='nav-item active'>
                                                <a href="/">推荐</a>
                                            </li>
                                            <li className='nav-item'><a href="/?sort=newest">最新</a>
                                            </li>
                                            <li className='nav-item'><a href="/?sort=three_days_hottest">热榜</a>
                                            </li>
                                        </ul>
                                    </nav>
                                </div>
                                <div className='entry-list-wrap'>
                                <div className='xitu-skeleton xitu-skeleton-animated'>
                                    <div className='xitu-skeleton-item' >
                                         <div className='xitu-skeleton-content' >
                                            <div className='xitu-skeleton-line' ></div>
                                            <div className='xitu-skeleton-line' ></div>
                                            <div className='xitu-skeleton-line' ></div>
                                            <div className='xitu-skeleton-line' >
                                    </div></div></div></div>
                                </div>
                            </div>
                        </div>
                        <aside className='index-aside aside'>
                            <div className='signin-tip signin'>
                                <div className='first-line'>
                                    <div className='icon-text'>
                                        <span className='title'>晚上好</span>
                                        <div className='second-line'>点亮在社区的每一天</div>
                                    </div>
                                    <button className='signin-btn btn'><span className='btn-text'>去签到</span></button>
                                </div>
                            </div>
                            <div className='sidebar-block banner-block'></div>
                            <div className='sidebar-block banner-block'></div>
                            <div className='sidebar-block banner-block app-download-sidebar-block'></div>
                            <div className='sidebar-block user-block'></div>
                            <div className='sidebar-block link-block'></div>
                            <div className='index-aside-footer'></div>
                        </aside>
                    </div>
                </div>
            </div>
        </main>
</div>
      </div>
    </>
  )
}
